### PR TITLE
Fix small bugs

### LINKED ISSUE #353: Channels: On scrolling down the Channels, the spacing is not consistent
1. Open the Arcade App on Android
2. Go to the Channels page and scroll down to it
3. Notice the spacing between the channels is not consistent

AR: The spacing between the channels is not consistent
ER: The spacing between the channels should display invariably

https://qatester-mailinator.tinytake.com/msc/ODQzMDM5M18yMTcyNzE4OA

### LINKED ISSUE #369: Chat: The chat messages overlap each other for a second while loading the group chat.
1. Open the Arcade App on Android as a logged-in user
2. Go to the Home screen
3. Open any group chat and notice the overlapping of chat while loading the chat.

AR: The chat messages overlap each other while loading on the user's screen.
ER: The user should see the chat messages load and appear on the screen clearly and without any distortion or overlap.
Video: https://qatester-mailinator.tinytake.com/msc/ODQ0MDcwNV8yMTc0MDU2MA

### LINKED ISSUE #372: Channel: In channel page different profile image is displaying in compare to profile
1. Open the Arcade App on Android.
2. Open the chat and check the image
3. Click on image and click on it
4. On profile page the check the user image is different

AR: Different images are displaying in chat and profile
ER: Profile image should not change in chat
Video: https://qatester-mailinator.tinytake.com/msc/ODQ0MjM2NV8yMTc0MjU3NA

### LINKED ISSUE #374: Profile: Profile image and display name is changing automatically on restarting the app
1. Open the Arcade App on Android.
2.  Go to profile page
3. Go to edit profile and add profile image and change display name
4. Update image and display name
5. Restart the app and notice recently updated image and name are changed automatically

AR: Profile image and display name is changing automatically on restarting the app
ER: Image and name update by user should not change automatically
Video:  https://qatester-mailinator.tinytake.com/msc/ODQ0NjE1OV8yMTc0NzU4NA

### LINKED ISSUE #377: Contact list: By default user "kima" is appearing fir every user
1. Create new user
2. Go to contact list
3. Refresh the page
4. Notice the user "kima" is appearing

Video is attached

https://github.com/ArcadeLabsInc/arcade/assets/5452850/aa78a239-2267-4181-9b2b-2328aa505386

### PR DESCRIPTION
**Pull request by reyamir**
**Changes**

- Rename `contact picker` screen to `invite` screen
- In home screen, add fetch invites (from private channels) to pull to refresh function
- In contacts screen, use pull to refresh instead of refresh button, pull to refresh not work before, but I figure how to fix it
- When user login, also clear contacts and channels cache, close #377 #391
- In profile screen, auto refetch user's profile when screen is focus, make sure alway up to date, close #374 
- Consistent default image, close #372 
- Increase default item's height for flashlist, close #369
- Update discover channels screen, move filter function to outside flashlist, fix collision error, close #353 
- Update ui for invite screen
- Update some texts for consistent

### CODE REVIEW

File: app/screens/ChannelsScreen.tsx [hunk 1]
```diff
@@ -86,7 +86,12 @@ export const ChannelsScreen: FC<ChannelsScreenProps> = observer(function Channel
     }
 
     async function initChannels(prev) {
-      const res = await channelManager.listChannels(true)
+      let res = await channelManager.listChannels(true)
+
+      // filter
+      res = res.filter((el) => el.name && isImage(el.picture) && el.is_private)
```
Comment (earonesty) [inline app/screens/ChannelsScreen.tsx:92]: what if there is no picture?   or no name?  or it's a public channel?   why are we removing this from the system?

File: app/screens/ContactPickerScreen.tsx [hunk 2]
```diff
@@ -51,9 +51,8 @@ export const ContactPickerScreen: FC<ContactPickerScreenProps> = observer(
     const [custom, setCustom] = useState([])
 
     const navigation = useNavigation<any>()
-    const contacts = useUserContacts()
 
-    const data = contacts.concat(custom)
+    const data = custom.concat(getContacts)
```
Comment (earonesty) [inline app/screens/ContactPickerScreen.tsx:55]: if you need to do this then there is a bug saving contacts that has to be fixed in arclib.

File: app/screens/ContactPickerScreen.tsx [hunk 3]
```diff
@@ -117,17 +116,20 @@ export const ContactPickerScreen: FC<ContactPickerScreenProps> = observer(
     }
 
     const addCustomContact = async (data) => {
-      let pubkey = data.pubkey
+      let pubkey = data.pubkey.trim()
```
Comment (earonesty) [inline app/screens/ContactPickerScreen.tsx:119]: this function should be this:

```
  const addCustomContact = async () => {
    let pubkey: string = customContact.trim()
    try {
      pubkey = await resolvePubkey(pubkey)
    } catch (e) {
      alert(`Invalid contact: ${e}`)
    }
    try {
      addContact({ pubkey, legacy: true, secret: false }, mgr)
      navigation.goBack()
    } catch (e) {
      alert(`Invalid contact: ${e}`)
    }
  }
```

if you do not call addContact, it will not be saved for real.  it will only be in mobx state tree, and if you log out and log in again, you will lose all your contacts

File: app/screens/ContactPickerScreen.tsx (hunk 2 above)
Comment (reyamir) [reply app/screens/ContactPickerScreen.tsx:55]: ah, this screen is just invite screen, when user add custom contact, it just add it to selected list to send invite, it not add follow to this custom contact

I put custom.contact before it will show custom on top of the list instead of bottom

File: app/screens/ChannelsScreen.tsx (hunk 1 above)
Comment (reyamir) [reply app/screens/ChannelsScreen.tsx]: I've updated it, just get only public channel then merge both array and remove duplicate 
```
// remove private channel
res = res.filter((el) => !el.is_private)

// merge array, remove dup
const final = [...new Map([...prev, ...res].map((el) => [el.id, el])).values()]
```
