### PR TITLE
Fixes for v3.0.1

### LINKED ISSUE #303: Direct message: No messages appearing even message is sent
1. Open any user profile
2. Send direct message
3. Go to chat screen from bottom options
4. Open the chat (It will be at top )
5. Direct message is empty

Video is attached 

https://github.com/ArcadeLabsInc/arcade/assets/5452850/ddcc5f7c-6370-41ec-85d2-1689797c2dc0

### LINKED ISSUE #327: Home page: The newly created channel is not displaying at the top of the homepage
1. Open the Arcade app on Android
2. Create a new channel 
3. Go back to home page
4. Notice newly created channel is not displaying at the top of the home page

AR: The newly created channel is not displaying at the top of the homepage
ER:  Latest created channel should display at the top

https://github.com/ArcadeLabsInc/arcade/assets/5452850/265a2283-5531-4a11-a19b-635e900d7a1f

### LINKED ISSUE #353: Channels: On scrolling down the Channels, the spacing is not consistent
1. Open the Arcade App on Android
2. Go to the Channels page and scroll down to it
3. Notice the spacing between the channels is not consistent

AR: The spacing between the channels is not consistent
ER: The spacing between the channels should display invariably

https://qatester-mailinator.tinytake.com/msc/ODQzMDM5M18yMTcyNzE4OA

### LINKED ISSUE #356: Chat: Reply attachment text alignment is not proper on the box
1. Open the Arcade App on Android as a logged-in user
2. On the home page tap on any channel that has messages on it.
3. Drag horizontally any message sent by other users.
4. Check the reply attachment text.

AR: Reply attachment text alignment is not proper on the box
ER: Reply attachment text alignment should be proper on the box

https://qatester-mailinator.tinytake.com/msc/ODQzMTU2M18yMTcyODYyMw

### LINKED ISSUE #367: Contact Suggestion screen: While scrolling an error message is appearing in contact suggestion screen
1. Open the Arcade App on Android as a logged-in user
2. Go to the Home screen
3. Tap on the contact icon on the bottom nav bar.
4. Tap on the Add button on the top right corner of the screen.
5. Contact suggestion screen will open, now scroll down

AR: While scrolling an error message is appearing in contact suggestion screen
ER: No error message should display

image

### PR DESCRIPTION
**Pull request by reyamir**
**Changes**

- Refactor relay provider
- Fix reply not work in some case
- Fix wrong direct message route param cause users chat with themself, instead of other user, close #303 
- (android only), remove padding in text, close #356 
- Update channels screen, close #353 
- In home screen, make sure all items sorted by last message time, close #327 
- Fix #367

### CODE REVIEW

File: app/models/UserStore.ts [hunk 1]
```diff
@@ -115,8 +119,14 @@ export const UserStoreModel = types
     get getMetadata() {
       return self.metadata
     },
-    get getPrivMesages() {
-      return [...new Map(self.privMessages.slice().map((item) => [item.pubkey, item])).values()]
+    get getChats() {
+      const chats = getSnapshot(self.privMessages)
+      chats.forEach((chat) => {
+        if (chat.pubkey === self.pubkey) {
+          chat.pubkey = chat.tags.find((el) => el[0] === "p")[1]
```
Comment (earonesty) [inline app/models/UserStore.ts:126]: the tag is the recipient, pubkey is sender.

now you don't know who sent the message

no way this can render right

**Review by earonesty — CHANGES_REQUESTED** [review]

File: app/models/UserStore.ts (hunk 1 above)
Comment (reyamir) [reply app/models/UserStore.ts:126]: it render fine, it made it for this case
(Home Screen)
```
current user -> send message to A -> A not response -> last message display in home screen is current user
current user -> send message to B -> B not response -> last message display in home screen is current user too
```
so I made it get recipient for this case to prevent duplicate items in home screen, and ignore the rest
message's content will not change, this behavior similar to telegram too

Screenshot 2023-07-14 at 21 34 55
